### ISSUE TITLE
Non-solid blocks: painful to mine

### ISSUE THREAD

**Issue by purpleposeidon** [Direwolf20-MC/MiningGadgets#10]
Eg, in hole with ladders, mining the ladder tries to suffocate you.

**Comment by MichaelHillcox** [comment]
Yeah, this is due to the bounding box of the render block being the size of a block. I can see if we can mimic the bounding box of the block but I'm not sure how simple it is to do.

**Comment by Direwolf20-MC** [comment]
Not a great way to fix this unfortunately. I can mimic the collision box of the block we're mining, but unfortunately that doesn't kick in until a tick or 2 after the mining has started on account of the tile entity not being formed yet. So you still take some damage and get pushed around a little until the TE is there and updates the bounding box. 

I'm gonna close as a 'too bad so sad' since its probably non trivial to fix. Besides, who mines out the ladder they're climbing on?!

If someone has a better solution LMK :)
