### ISSUE TITLE
(BUG) Mining gadget mining insanely slow

### ISSUE THREAD

**Issue by OmegaAlpha83** [Direwolf20-MC/MiningGadgets#150]
my mining gadget has max range speed all that its tier 3 I had just updated the Mod pack ATM6 on the server and I had my mining gadget in my inventory that's when i noticed new model and textures I'm like cool but when I mine in a straight line its fine but when I drag my curser across blocks then stop on one pair of blocks it mines insanely slow. this is  #really annoying when mining and I may have to find a new method

**Comment by MichaelHillcox** [comment]
Hmm odd, might be a bug in the way the max durability of blocks is handled.

**Comment by DocterDum** [comment]
Just so you know I'm getting the same issue on DW20 1.16 Pack

**Comment by MichaelHillcox** [comment]
Either of you about make a small video to show your issue?

**Comment by MichaelHillcox** [comment]
Thanks, that's really helpful, hopefully I can track this down and get it fixed :D

**Comment by DocterDum** [comment]
No problem. Thanks for your awesome work :)

If it helps, the issue doesn't happen when you target a different face (of the same or a different block), it only occurs on the same face of a different block.

**Comment by jmdev91** [comment]
I'm experiencing this too, in my own custom mod list. It appears to only happen with the 3x3 upgrade and only when you change the direction you're looking while continuing to mine. Once it occurs, you have to wait for the block animation (shrink or fade) to reset before those blocks can be mined at the intended speed, but if you look back in the direction you started in it will mine properly. That makes it sound like a vector problem, but I can't seem to find where that upgrade is processed in the code so that's as far as I've gotten.

**Comment by fosslinux** [comment]
Would it be possible to get a release for 1.16 from that commit? This bug makes the mining laser extremely difficult to use in 1.16. (Particularly in the Vault Hunters modpack where it would have significant utility if this bug was fixed).

(I can build it myself, but before recommending my build to those affected, I wanted to see if an official build could be made).

**Comment by the-impossible9** [comment]
@fosslinux, any chance you can share your build with the fix?

**Comment by MichaelHillcox** [comment]
I'll sort this Wednesday / Thursday

**Comment by fosslinux** [comment]
> @fosslinux, any chance you can share your build with the fix?

I would rather not make it generally available. That is not good practice. It is quite simple to build yourself, if you have a bit of coding experience.

**Comment by MichaelHillcox** [comment]
If you've got the code sorted, you could make a Pr 😉

**Comment by the-impossible9** [comment]
Sorry I dont have much coding experience. I dont mind waiting a few days though :)

**Comment by MichaelHillcox** [comment]
It's processing now, you can get it here once it's approved https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/3902532

**Comment by the-impossible9** [comment]
Thank you!
I'm playing on a server. Do you know if I need to update the client or service or both?

**Comment by MichaelHillcox** [comment]
Both
