### ISSUE TITLE
[1.20] Crashes when mining near other mod's blocks

### ISSUE THREAD

**Issue by Blockguy24** [Direwolf20-MC/MiningGadgets#216]
Not exactly sure how to reproduce this but I have a few crash reports:

[crash-2023-07-22_11.23.51-client.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/12135383/crash-2023-07-22_11.23.51-client.txt)
[crash-2023-07-22_11.10.28-client.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/12135384/crash-2023-07-22_11.10.28-client.txt)
[crash-2023-07-21_15.00.28-client.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/12135385/crash-2023-07-21_15.00.28-client.txt)
[crash-2023-07-18_21.15.35-client.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/12135386/crash-2023-07-18_21.15.35-client.txt)
[crash-2023-07-18_21.13.19-client.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/12135387/crash-2023-07-18_21.13.19-client.txt)
[crash-2023-07-18_19.28.51-client.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/12135388/crash-2023-07-18_19.28.51-client.txt)

**Comment by trevorjd** [comment]
I had what appears to be the same error just now.  Running FTB Unstable 1.20.1 and pillaging my way through a mod Cataclysm 'fortress' in the end.  Was drilling through a wall when I got the attached crash.

[crash-2023-07-23_22.29.03-client.txt](https://github.com/Direwolf20-MC/MiningGadgets/files/12138761/crash-2023-07-23_22.29.03-client.txt)

**Comment by Zirpoo** [comment]
I have the same problem. I use 3x3, magnet, freezing, efficiency and fortune upgrades but it seems to be some problem with particles or something I don't know...
I gave up using this mod since it's just too annoying crashing non stop because I mine and there is a nest block from another mod and I can't pickup sands.

But the crash on the screenshot is not from picking up sand. It happens on special cases of blocks

![Capture d’écran 2023-08-05 212807](https://github.com/Direwolf20-MC/MiningGadgets/assets/19390838/e604cf6f-5d46-4f95-a121-8290892be6d6)

**Comment by Direwolf20-MC** [comment]
Should be resolved by: 
https://github.com/Direwolf20-MC/MiningGadgets/commit/bdf75afded15b23d0a1ee74b1a7caaa3e7ba0dc8
