### ISSUE TITLE
Boring Mode?

### ISSUE THREAD

**Issue by swestrup** [Direwolf20-MC/MiningGadgets#236]
I find it very annoying that the beam only traces a single block from the tip of the gun to the target. This means that, when mining 3x3 or bigger, you need to fill in the center block in order to mine out blocks around it. I would love a mode whereby it will check the NxN around the center block at each point along, and mine out any blocks that should not be there. I would be perfectly okay with this requiring an add-on or an increase in power usage, or both.

**Comment by Anoyomouse** [comment]
I don't know if this is technically possible without creating a load of lag .. the 3x3 (and 5x5 and 7x7) work by basically drawing a line from the player to the first block you encounter, and then spreading out from that block.

In order to implment this we'd effectively have to scan every block in front of the player until we found a valid one to remove, in the worst case (the tunnel is empty) it would take a scan of more than 225 (range 5, and 9 blocks per step) blocks per tick, and with a 7x7, that's ... 1225 blocks-ish, i'm sure it's more.

**Comment by MichaelHillcox** [comment]
Yeah, I agree with @Anoyomouse this isn't something that is practical... I know the issue you're describing well but the performance impact of this kinda system would be too much to consider adding it. Sorry about that
