### ISSUE TITLE
freezing upgrade still deleting tile entities

### ISSUE THREAD

**Issue by jlp1528** [Direwolf20-MC/MiningGadgets#241]
Tested with waterlogged chest in Direwolf20 pack 1.12.0 including Mining Gadgets 1.15.6. Refer to https://github.com/Direwolf20-MC/MiningGadgets/issues/233

**Comment by Anoyomouse** [comment]
If you check the releases on CurseForge, 1.15.7 is actually the latest version, but it's "older" then 1.15.6, so it says that's the latest

https://www.curseforge.com/minecraft/mc-mods/mining-gadgets/files/4864219 <-- 1.15.7
@MichaelHillcox Sorry for the ping, but is it possible to either re-upload 1.15.7, or to delist 1.15.6 (maybe say 1.15.6 is beta) so that 1.15.7 becomes the latest release version to fix this?

On curse forge, you can see 1.15.7 is not the latest
![image](https://github.com/Direwolf20-MC/MiningGadgets/assets/4417100/dbfd8741-2be2-4c67-9f1c-23aa6be79d00)

**Comment by Direwolf20-MC** [comment]
Yea thats a super weird curseforge thing :). I'll see if I can get it fixed somehow. But the original bug here is fixed.
