### ISSUE TITLE
crash launcher premium 1.14.4 forge 107

### ISSUE THREAD

**Issue by tiphilou17** [Direwolf20-MC/MiningGadgets#44]
One of my player but other not crash

crash withis this : "The game crashed whilst initializing game
Error: java.lang.IllegalStateException: GLFW error 65539: Invalid key 3"

https://gist.github.com/tiphilou17/6ed8e9eeb00357b31b4cdc96cdf2f342

**Comment by MichaelHillcox** [comment]
I'll update our forge version and see if I get any errors, thanks :+1:

**Comment by Bass2style** [comment]
hi,

i'm "upping" this report, because it's still happening to me, both on 1.14 and 1.15 builds, on any Forge build.

happens also on ATM4 and 5, on those two, MiningGadgets seems not the only responsible of this crash, but on my custom pack, with mods added one-by-one, when i enable MG, it's crashing with that error.

**Comment by xD-Matriox** [comment]
Bass2style I have looked and figured out that along with Mining Gadgets, Building Gadgets Also caused the issue. I removed the mod and it started working, I'm referring to ATM 4 btw.

**Comment by Bass2style** [comment]
yeah, noticed it, in addition, To The Bat Poles and Advanced Hook Launcher seems to produce the same bug (or something not far from it) on ATM5 here. need to check that out if ForgeEnderTech mods errors give more usefull infos to fix that.

**Comment by MichaelHillcox** [comment]
Closed in preference of #49 (same issue :+1:)
